print("Welcome to band name generator!")
print("What city did you grow up in?")
city = raw_input()
print("What is the name of your pet?")
pet = raw_input()
print("Your band name could be: " + city + " " + pet)